package de.stsFanGruppe.templatebuilder.gui;

import java.util.Set;
import de.stsFanGruppe.templatebuilder.external.ImporterFramework;
import de.stsFanGruppe.templatebuilder.external.jtraingraph.JTrainGraphImporter;
import de.stsFanGruppe.templatebuilder.strecken.*;
import de.stsFanGruppe.templatebuilder.zug.*;
import java.awt.SystemColor;

/**
 *
 * @author DevonFrosch
 */
public class BildfahrplanGUI extends javax.swing.JFrame
{
	/**
	 * Creates new form BildfahrplanGUI
	 */
	public BildfahrplanGUI()
	{
		initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents()
	{
		java.awt.GridBagConstraints gridBagConstraints;
		
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel2 = new BildfahrplanZeichner(new BildfahrplanConfig(300, 600), this);
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("BildfahrplanGUI");
		setLocationByPlatform(true);
		setPreferredSize(new java.awt.Dimension(800, 500));
		getContentPane().setLayout(new java.awt.GridBagLayout());
		
		jPanel1.setBackground(SystemColor.menu);
		jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jPanel1.setMaximumSize(new java.awt.Dimension(32767, 100));
		jPanel1.setMinimumSize(new java.awt.Dimension(500, 100));
		jPanel1.setName(""); // NOI18N
		
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 736, Short.MAX_VALUE)
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 100, Short.MAX_VALUE)
		);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		getContentPane().add(jPanel1, gridBagConstraints);
		
		jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		
		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		//jPanel2.setMinimumSize(new java.awt.Dimension(100, 200));
		jPanel2.setName(""); // NOI18N
		
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 717, Short.MAX_VALUE)
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGap(0, 1000, Short.MAX_VALUE)
		);
		
		jScrollPane1.setViewportView(jPanel2);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		getContentPane().add(jScrollPane1, gridBagConstraints);
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	public void setHeight(int height)
	{
		javax.swing.GroupLayout layout = (javax.swing.GroupLayout) jPanel2.getLayout();
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, height, Short.MAX_VALUE));
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			javax.swing.UIManager.setLookAndFeel( javax.swing.UIManager.getSystemLookAndFeelClassName() );
		}
		catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(BildfahrplanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		
		//</editor-fold>
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			// Daten importieren
			try
			{
				String file = "testdaten/2014-02-24_KBS110_AHAR-HC.fpl";
				//String file = "testdaten/Bildfahrplan_Eifelbahn.fpl";
				ImporterFramework imp = new ImporterFramework(new JTrainGraphImporter());
				Streckenabschnitt streckenabschnitt = imp.importStreckenabschnitt(file);
				//System.out.println(streckenabschnitt.toXML());
				BildfahrplanGUI bfp = new BildfahrplanGUI();
				bfp.setVisible(true);
				bfp.jPanel2.setStreckenabschnitt(streckenabschnitt);
				
				Set<Fahrt> fahrten = imp.importFahrten(file, streckenabschnitt, new Linie("1"));
				/*System.out.println("<fahrten>");
				fahrten.forEach((Fahrt f) -> System.out.println(f.toXML("  ")));
				System.out.println("</fahrten>");
				//*/
				bfp.jPanel2.zeichneFahrten(fahrten);
				bfp.jPanel2.optimizeHeight();
			}
			catch(Exception e)
			{
				e.printStackTrace();
			}
		});
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel jPanel1;
	private BildfahrplanZeichner jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
}
